CREATE TABLE mcp_server
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    base_url       VARCHAR(255),
    endpoint       VARCHAR(255),
    transport_type SMALLINT,
    CONSTRAINT pk_mcpserver PRIMARY KEY (id)
);